# Generated by Django 3.0.6 on 2020-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donor_name', models.CharField(max_length=100)),
                ('Contact_no', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Blood_group', models.CharField(max_length=100)),
                ('Rh_factor', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
