# Generated by Django 3.0.6 on 2020-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200515_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Contact_no',
            field=models.IntegerField(),
        ),
    ]
