# Generated by Django 3.0.6 on 2020-05-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200515_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Blood_group',
            new_name='Bloodgroup',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Contact_no',
            new_name='Contactno',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Donor_name',
            new_name='Donorname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Rh_factor',
            new_name='Rhfactor',
        ),
    ]
