# Generated by Django 3.0.6 on 2020-05-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200517_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Bloodgroup',
            new_name='Blood_group',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Contactno',
            new_name='Contact_no',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Donorname',
            new_name='Donor_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Rhfactor',
            new_name='Rh_factor',
        ),
    ]
