# Generated by Django 3.0.6 on 2020-05-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200517_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Confirm_Password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='Password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
