# Generated by Django 3.0.6 on 2020-05-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200518_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Confirm_Password',
        ),
    ]
