# Generated by Django 3.0.6 on 2020-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_register_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='blood_amt',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
